name: Run Android build

on: workflow_dispatch
#  workflow_dispatch:
#  push:
#    paths:
#      - 'app/**'

env:
  ANDROIDSDK_VERSION: 12266719

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''
          cmdline-tools-version: ${{ env.ANDROIDSDK_VERSION }}
          log-accepted-android-sdk-licenses: false
        
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          key: AndroidSDK-${{ env.ANDROIDSDK_VERSION }}
          path: |
            ~/.android
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/release.jks
          
      - uses: actions/checkout@v6
        id: checkout
      
      - name: Gradle Build
        env:
          KEYSTORE_PATH_RELEASE: ${{ runner.temp }}/keystore/release.jks
        run: ./gradlew --no-daemon clean assembleRelease
        
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: Build Artifacts
          path: app/build/outputs/
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
          allowUpdates: true
          tag: "1.3.0+1"
          commit: "${{ steps.checkout.outputs.commit }}"
          body: "${{ steps.checkout.outputs.commit }}"
